apiVersion: v1
kind: Namespace
metadata:
  name: darwin
  labels:
    name: darwin
    environment: production
    managed-by: kubectl

---
apiVersion: v1
kind: Namespace
metadata:
  name: darwin-monitoring
  labels:
    name: darwin-monitoring
    environment: production

