apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: darwin-core
  namespace: darwin-core
  labels:
    app: darwin-core
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - core.agourakis.med.br
    secretName: darwin-core-tls
  rules:
  - host: core.agourakis.med.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: darwin-core
            port:
              number: 8000

